version: '3'
services:
  conquest:
    build:
      context: .
      dockerfile: conquest.Dockerfile
    restart: always
    ports:
      - 5678:5678
    volumes:
      - /mnt/bucket/dicom/conquest:/mnt/data
