version: '3'
services:
  conquest:
    build:
      context: .
      dockerfile: conquest-debian.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - TZ="American/New_York"
    ports:
      - 5678:5678
    volumes:
      - /mnt/cup/PNI-facilities/fMRI//dicom/conquest:/mnt/data
      - /mnt/puddle/PNI-archive/dicom:/mnt/archive
    labels:
      - "deck-chores.conquest-dailysweep.command=/opt/scripts/ConquestArchive.sh"
      - "deck-chores.conquest-dailysweep.cron=3 0 0"


networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: conquestnet